Fix/add pages
SamagraX-Stencil/stencil_docs pull request #17
Opened 2024-06-05 08:45 UTC by ankitmlesmagico

2024-06-05 12:38 UTC, biratdatta requested changes
Quality of Life changes because it's better to store numeric values as numbers rather than strings.

2024-06-05 12:38 UTC, biratdatta commented on docs/pages/otpPage.md
> +     "resendOtpTimer": "30",
"resendOtpTimer": 30,

2024-06-05 12:38 UTC, biratdatta commented on docs/molecules/chatui.md
> +      "transliterationSuggestions": "3",
"transliterationSuggestions": 3,

2024-06-05 23:19 UTC, ankitmlesmagico commented on docs/pages/otpPage.md
> +     "resendOtpTimer": "30",
done

2024-06-05 23:19 UTC, ankitmlesmagico commented on docs/molecules/chatui.md
> +      "transliterationSuggestions": "3",
done

2024-06-10 11:49 UTC, prtkjakhar commented on docs/stencilweb/overview.md
> +A `Stencil Web` is a libraray made up of various molecules and pages. It represents a more intricate UI element designed to fulfill a specific function within an application's interface. For example,
`library` spell error

2024-06-13 05:10 UTC, ankitmlesmagico commented
done

2024-06-13 05:10 UTC, ankitmlesmagico commented on docs/stencilweb/overview.md
> +A `Stencil Web` is a libraray made up of various molecules and pages. It represents a more intricate UI element designed to fulfill a specific function within an application's interface. For example,
done

2024-06-13 17:38 UTC, merged